### ISSUE TITLE
Docs: Download instructions in "Installation guide" leads to "command not found" error

### ISSUE THREAD

**Issue by pepawel** [NethermindEth/sedge#107]
**Describe the bug**
Download instructions in "Installation guide" doesn't include -o/--output options, therefore "sedge" binary is not being created.
"Complete quickstart guide" includes correct options. Therefore wget/curl line from "Complete quickstart guide" should be copied to "Installation guide".

**To Reproduce**
1. Open [Installation guide](https://docs.sedge.nethermind.io/docs/quickstart/install-guide)
2. Perform steps 1-4.
3. Observe "command not found" error.

**Expected behavior**
Binary should be named `sedge` not `sedge-v0.3.0-linux-amd64`.

**Comment by cbermudez97** [comment]
Hi @pepawel . Thanks for opening this issue. Will fix our docs. 👍
