### ISSUE TITLE
deposit_data.json incorrect for Gnosischain

### ISSUE THREAD

**Issue by GLCNI** [NethermindEth/sedge#168]
Run through setup with fully synced, EL+CL clients and imported validators awaiting activation.
However, seems that the `deposit_data.json` is the ‘wrong network’

**To Reproduce**
Run through set up normally to get working EL & CL, and validator client, awaiting activation
Keys Generated 
`sedge keys --network gnosis `

**Screenshots**
![image](https://user-images.githubusercontent.com/67609618/202715139-7c967464-0dbb-4f3e-b01a-1bead94864e0.png)

**Comment by cbermudez97** [comment]
Hi @GLCNI. Thanks for reporting, we had the wrong fork version in our configs [here](https://github.com/NethermindEth/sedge/blob/feature/windows-support/configs/init.go#L57). Will upload a fix for that. A quick fix for your case would be changing the `deposit_data.json` the line with `"fork_version": "0000006f"` to `"fork_version": "00000064"`.
