### ISSUE TITLE
Add ultra sound relay

### ISSUE THREAD

**Issue by JustinDrake** [NethermindEth/sedge#222]
Consider adding [the ultra sound relay](https://relay.ultrasound.money) in addition to the FlashBots relay :)

https://github.com/NethermindEth/sedge/blob/0dcdb138d23c818baa263873e06ab97820c5c6b5/templates/envs/mainnet/env_base.tmpl#L5

**Comment by AntiD2ta** [comment]
Hey, @JustinDrake thanks for sharing. Would you like to be able to choose between recommended relays via prompt or having Sedge tell you a list of relays so you can go and use the flag to use a relay different from default? There can only be one default relay.
