### ISSUE TITLE
v.1.0.0, Teku Consensus client keeps restarting

### ISSUE THREAD

**Issue by BMItr** [NethermindEth/sedge#268]
**Describe the bug**
I just tested the newest version 1.0.0! Great work so far! also a very nice interactive mode (cli).

I used a setup with nethermind & teku in the past (sedge 0.5  & 0.6 had now problems).
With the newest version(1.0.0) I get a restarting/crashing teku docker container.
Logs are saying: **Cannot write to folder /var/lib/teku/validator/slashprotection**  even it is supposed to write to ./sedge-data (default).

I have not changed any locations, mount points or .env configs (default).
I only used the CLI.

I also tested it with other consensus clients, no problems so far!
Must be a specific teku problem.

Kind regards & keep up your great work!

**To Reproduce**
1. Go to 'sedge cli'
2. Chose Gnosis
3. Chose Nethermind
4. Chose TEku
...

**Expected behavior**
At least 2 running containers

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubu22.04
 - Sedge 1.0.0

**Comment by adriantpaez** [comment]
Thanks for the feedback @BMItr! Are you using a new (empty) `sedge-data` dir or one with some old data inside?

**Comment by BMItr** [comment]
@adriantpaez everything from scratch (new & empty sedge-data).

**Comment by BMItr** [comment]
I would love to answer of course I run it with sudo 🐤 
I started the cli without sudo. And later I ran 
![image](https://user-images.githubusercontent.com/46747780/227213508-94b6f102-e097-4280-b422-936dcc45bf74.png)
with sudo. This was not sufficent, as the permission was already set.

I just retried with _sudo sedge cli_  and everything works fine! 👌 

Ticket can be closed. Thx for your quick support and have a good week! 🥇

**Comment by cbermudez97** [comment]
Thanks, good that it worked out for you. However, Sedge is not meant to be run as sudo but it will still work. The folders were probably created with different permissions than it was used later to start the services. In general, over a specific `sedge-data` you should use the same user/permissions for all sedge commands.

**Comment by BMItr** [comment]
👌
