### ISSUE TITLE
Nethermind 1.21.0 broke sedge

### ISSUE THREAD

**Issue by Khepesh** [NethermindEth/sedge#330]
**Describe the bug**
Can't upgrade to Nethermind 1.21.0 and will not be able to in future releases.

**To Reproduce**
Upgrade Nethermind in 1.21.x

**Comment by stdevMac** [comment]
Hello @Khepesh ! Thanks for reaching us, can you share more logs of what is happening? provide more details in general of the error you are getting? Thanks in advance!

**Comment by Khepesh** [comment]
I'm no expert but to make it short I got a "DNS issue" error and the validator never start, I thought it would be a known issue related to 1.21.0's update breaking change: 

⚠️ IMPORTANT

The Nethermind executable has been renamed from Nethermind.Runner to nethermind
The Nethermind Launcher executable has been renamed from Nethermind.Launcher to nethermind-launcher
The Nethermind CLI executable has been renamed from Nethermind.Cli to nethermind-cli
The Docker images entry points have been updated accordingly.
Please update your setups accordingly, if any.

**Comment by stdevMac** [comment]
Can you please show the outputs of `sedge logs execution`?

**Comment by stdevMac** [comment]
In any case we are working on a release with the latest nethermind version available soon, so should solve your issue 🙏

**Comment by Khepesh** [comment]
got no issue actually coz i went back to 1.20.4 but here is what i got with 1.21.1 : 

![image](https://github.com/NethermindEth/sedge/assets/26637768/b158d3b7-d67b-4001-bba7-ca7972ad9eb2)

**Comment by stdevMac** [comment]
@Khepesh which version of sedge you are using? We fixed that problem in current latest version of sedge

**Comment by Khepesh** [comment]
latest One, 1.2.3

**Comment by cbermudez97** [comment]
Hi @Khepesh looks like the Nethermind configuration that is being used by Sedge is using `--config=xdai` instead of `--config=gnosis`. This is a expected issue. To update you can go inside the `sedge-data` directory and modify the `docker-compose.yml`. Inside find the `execution` service and change the `xdai` config to `gnosis`.

Please let us know if this change allow you to upgrade to Nethermind 1.21 👍

**Comment by Khepesh** [comment]
Hi,
It looks like it's working, but it's doing a full sync (it changed the db folder name from xdai to gnosis, didn't take the "risk" to just rename it)
Still at ~33% so there are still some hours left to confirm it's working perfectly.
