### ISSUE TITLE
Lodestar ports configuration

### ISSUE THREAD

**Issue by MarekM25** [NethermindEth/sedge#357]
The Lodestar configuration should be changed in Sedge. Related issue: https://github.com/NethermindEth/nethermind/issues/5660

@benaadams reported about Lodestar
I had a look at their code and they take two ports, they only make engineapi requests via the engine port and others via rpc port; if the ports are set the same then they won't sent the jwt so will still be unauth

**Comment by AryanGodara** [comment]
Can I work on this issue @MarekM25? I've been going through the linked issue, it looks like I might be able to tackle this one (with some help form you 😅)

**Comment by cbermudez97** [comment]
Solved in https://github.com/NethermindEth/sedge/commit/2cc5c003591ca81fba6d9f0ac865430a1a1475e6 and released in https://github.com/NethermindEth/sedge/releases/tag/v1.3.1. Thanks 🙏
