### ISSUE TITLE
Ubuntu PPA

### ISSUE THREAD

**Issue by eliotstock** [NethermindEth/sedge#87]
**Is your feature request related to a problem? Please describe.**
At the moment I only see 'download the latest binary' and 'build from source' installation options in the docs. This makes sedge a bit of a non-starter for me because it's going to be my job to look out for new releases and upgrade to them. If you had an Ubuntu PPA that would happen automatically.

**Describe the solution you'd like**
Publish a Debian package on a PPA somewhere. I hear Polkadot clients have this working, if you need an example.

**Describe alternatives you've considered**
Watching the GH repo and downloading the binary again on every release.

**Additional context**
Without this, Sedge will have legacy versions running in the field for anyone who's not super on top of looking out for new releases.

**Comment by AntiD2ta** [comment]
Thanks a lot @eliotstock. We already have started working on this, although is taking some time. Homebrew installation method is almost ready though.
