### ISSUE TITLE
Docs: curl url slightly broken for the binary

### ISSUE THREAD

**Issue by eliotstock** [NethermindEth/sedge#89]
On this page:

https://docs.sedge.nethermind.io/docs/quickstart/install-guide

You use the following URL for the binary:

github.com/NethermindEth/sedge/releases/download/`<VERSION>`/sedge-v`<VERSION>`-`<OS>`-`<ARCH>`

Notice that in the first use of `<VERSION>`, there's no `v` in front but there is in the second `<VERSION>`. But we need `v` in both, actually.

I put `0.2.0` in place of both `<VERSION>`s and then ended up with a text file downloaded with the contents `Not Found`, which was confusing when I tried to run it.

**Comment by cbermudez97** [comment]
Hi @eliotstock and thanks for your contribution. Will update our docs with the correct URL.
